"""
FastAPI wrapper exposing the triage agent as POST /tickets.

Deliberately thin - all real logic lives in agent.py's triage_ticket().
This file's only job is translating HTTP <-> that function. This is the
separation-of-concerns decision from the README: the agent shouldn't
know or care how it was invoked, and neither entry point (this one,
main.py) should duplicate its logic.

Run locally:
    uvicorn api:app --reload

Then, from another terminal:
    curl -X POST http://127.0.0.1:8000/tickets \
      -H "Content-Type: application/json" \
      -d '{"message": "How much is the Glacier Skywalk tour for 2 people?"}'

Interactive API docs (auto-generated by FastAPI) are at
http://127.0.0.1:8000/docs once the server is running.
"""

from pathlib import Path
from typing import Optional

from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded

import github_kb
from agent import triage_ticket
from auth import require_cms_auth


def get_client_ip(request: Request) -> str:
    """Deliberately not using slowapi's own get_remote_address - it has a
    known bug (checks the header key "X_FORWARDED_FOR" instead of the
    real "X-Forwarded-For", so it never actually finds it) and would fall
    back to seeing Render's proxy IP for every request, which would
    silently turn this into a GLOBAL rate limit shared by every visitor
    instead of a per-visitor one. Real fix lives at the server layer
    instead: uvicorn's --proxy-headers flag (see README's Deploying
    section) correctly populates request.client.host with the true
    client IP before our code ever sees the request, so we just read it
    directly here - no header parsing of our own to get wrong."""
    return request.client.host if request.client else "unknown"


limiter = Limiter(key_func=get_client_ip)

app = FastAPI(
    title="Northstar Ticket Triage Agent",
    description="Triages a support ticket: resolves it with a cited reply, or escalates it with a specific reason.",
    version="0.1.0",
)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

ADMIN_DIR = Path(__file__).parent / "admin"


class DocUpdateRequest(BaseModel):
    content: str
    sha: str


class TicketRequest(BaseModel):
    message: str = Field(..., description="The raw text of the incoming support ticket.")
    ticket_id: Optional[str] = Field(
        None, description="Optional caller-supplied ID, echoed back unchanged so callers can correlate responses."
    )
    channel: Optional[str] = Field(None, description="Optional metadata - not used by the agent.")
    customer_name: Optional[str] = Field(None, description="Optional metadata - not used by the agent.")


class TicketResponse(BaseModel):
    ticket_id: Optional[str] = None
    action: str
    category: str
    reply: Optional[str] = None
    cited_docs: list[str] = []
    escalation_reason: Optional[str] = None


@app.post("/tickets", response_model=TicketResponse)
@limiter.limit("10/minute")
def create_ticket_triage(request: Request, ticket_request: TicketRequest) -> TicketResponse:
    if not ticket_request.message.strip():
        raise HTTPException(status_code=400, detail="message cannot be empty")

    try:
        result = triage_ticket(ticket_request.message)
    except RuntimeError as e:
        # e.g. missing API key - a real config problem, not a bad request
        raise HTTPException(status_code=500, detail=str(e))

    return TicketResponse(
        ticket_id=ticket_request.ticket_id,
        action=result.action,
        category=result.category,
        reply=result.reply,
        cited_docs=result.cited_docs,
        escalation_reason=result.escalation_reason,
    )


@app.get("/health")
def health_check():
    return {"status": "ok"}


@app.get("/cms", response_class=HTMLResponse)
def cms_page(username: str = Depends(require_cms_auth)):
    # Read from admin/, never static/ - this file must only ever be
    # reachable through this auth-gated route, not the public static mount.
    html = (ADMIN_DIR / "cms.html").read_text(encoding="utf-8")
    return HTMLResponse(content=html)


@app.get("/cms/docs")
def list_cms_docs(username: str = Depends(require_cms_auth)):
    return {"filenames": github_kb.list_valid_doc_filenames()}


@app.get("/cms/docs/{filename}")
def get_cms_doc(filename: str, username: str = Depends(require_cms_auth)):
    try:
        doc = github_kb.get_doc_content(filename)
    except ValueError as e:
        # Not in the whitelist - see github_kb.py for why this also
        # doubles as the path-traversal defense.
        raise HTTPException(status_code=404, detail=str(e))
    except RuntimeError as e:
        raise HTTPException(status_code=502, detail=str(e))
    return {"filename": doc.filename, "content": doc.content, "sha": doc.sha}


@app.put("/cms/docs/{filename}")
def update_cms_doc(
    filename: str,
    request: DocUpdateRequest,
    username: str = Depends(require_cms_auth),
):
    try:
        github_kb.update_doc_content(
            filename, request.content, request.sha, edited_by=username
        )
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except RuntimeError as e:
        # Covers both the sha-conflict case and other GitHub API errors -
        # github_kb.py's own message is already clear enough to surface
        # directly to the CMS UI.
        raise HTTPException(status_code=409, detail=str(e))
    return {"status": "saved"}


# Mounted last, deliberately - so the explicit routes above are matched
# first, and this only catches whatever's left (the guest UI at "/").
app.mount("/", StaticFiles(directory="static", html=True), name="static")
