"""
FastAPI wrapper exposing the triage agent as POST /tickets.

Deliberately thin - all real logic lives in agent.py's triage_ticket().
This file's only job is translating HTTP <-> that function. This is the
separation-of-concerns decision from the README: the agent shouldn't
know or care how it was invoked, and neither entry point (this one,
main.py) should duplicate its logic.

Run locally:
    uvicorn api:app --reload

Then, from another terminal:
    curl -X POST http://127.0.0.1:8000/tickets \
      -H "Content-Type: application/json" \
      -d '{"message": "How much is the Glacier Skywalk tour for 2 people?"}'

Interactive API docs (auto-generated by FastAPI) are at
http://127.0.0.1:8000/docs once the server is running.
"""

from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from agent import triage_ticket

app = FastAPI(
    title="Northstar Ticket Triage Agent",
    description="Triages a support ticket: resolves it with a cited reply, or escalates it with a specific reason.",
    version="0.1.0",
)


class TicketRequest(BaseModel):
    message: str = Field(..., description="The raw text of the incoming support ticket.")
    ticket_id: Optional[str] = Field(
        None, description="Optional caller-supplied ID, echoed back unchanged so callers can correlate responses."
    )
    channel: Optional[str] = Field(None, description="Optional metadata - not used by the agent.")
    customer_name: Optional[str] = Field(None, description="Optional metadata - not used by the agent.")


class TicketResponse(BaseModel):
    ticket_id: Optional[str] = None
    action: str
    category: str
    reply: Optional[str] = None
    cited_docs: list[str] = []
    escalation_reason: Optional[str] = None


@app.post("/tickets", response_model=TicketResponse)
def create_ticket_triage(request: TicketRequest) -> TicketResponse:
    if not request.message.strip():
        raise HTTPException(status_code=400, detail="message cannot be empty")

    try:
        result = triage_ticket(request.message)
    except RuntimeError as e:
        # e.g. missing API key - a real config problem, not a bad request
        raise HTTPException(status_code=500, detail=str(e))

    return TicketResponse(
        ticket_id=request.ticket_id,
        action=result.action,
        category=result.category,
        reply=result.reply,
        cited_docs=result.cited_docs,
        escalation_reason=result.escalation_reason,
    )


@app.get("/health")
def health_check():
    return {"status": "ok"}


# Mounted last, deliberately - so the explicit routes above are matched
# first, and this only catches whatever's left (the guest UI at "/").
app.mount("/", StaticFiles(directory="static", html=True), name="static")
